package com.github.yeriomin.workoutlog.Model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig exerciseTypeDaoConfig;
    private final DaoConfig exerciseDaoConfig;

    private final ExerciseTypeDao exerciseTypeDao;
    private final ExerciseDao exerciseDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        exerciseTypeDaoConfig = daoConfigMap.get(ExerciseTypeDao.class).clone();
        exerciseTypeDaoConfig.initIdentityScope(type);

        exerciseDaoConfig = daoConfigMap.get(ExerciseDao.class).clone();
        exerciseDaoConfig.initIdentityScope(type);

        exerciseTypeDao = new ExerciseTypeDao(exerciseTypeDaoConfig, this);
        exerciseDao = new ExerciseDao(exerciseDaoConfig, this);

        registerDao(ExerciseType.class, exerciseTypeDao);
        registerDao(Exercise.class, exerciseDao);
    }
    
    public void clear() {
        exerciseTypeDaoConfig.getIdentityScope().clear();
        exerciseDaoConfig.getIdentityScope().clear();
    }

    public ExerciseTypeDao getExerciseTypeDao() {
        return exerciseTypeDao;
    }

    public ExerciseDao getExerciseDao() {
        return exerciseDao;
    }

}
